version: '3.9'

services:
  wp:
    build:
      no_cache: true
      dockerfile: ./config/dev/Dockerfile
      context: .
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "0.2"
    #      memory: 3g
    environment:
      MODE: development
      WORDPRESS_DEBUG: 1
      XDEBUG_MODE: ${WORDPRESS_XDEBUG_MODE:-off}
      XDEBUG_CONFIG: client_host=host.docker.internal
    volumes:
      - ./wp/wp-content:/var/www/html/wp-content
      #- ./wp/wp-content/themes/afm:/var/www/html/wp-content/themes/afm
      #- ./wp/wp-content/plugins:/var/www/html/wp-content/plugins
      #- ./wp/wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp/.htaccess:/var/www/html/.htaccess
      - ./config/dev/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./xdebug:/tmp/xdebug
      - ./config/dev/apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 80:80
      - 443:80
    extra_hosts:
      - "assistant.local:host-gateway"

  db:
    volumes:
      - ./db:/var/lib/mysql

  # https-portal:
  #   environment:
  #     PROXY_BUFFERS: 0kb
  #     DOMAINS: 'localhost -> http://wp:80'
  #     STAGE: local
  #   volumes:
  #     - ./https-portal-data:/var/lib/https-portal
volumes:
  db:
  node_modules:
